name: assets_variation
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  http: ^1.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  auto_route: ^7.8.4
  gap: ^3.0.1
  flutter_localized_locales: ^2.0.5
  cached_network_image: ^3.3.1
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  freezed: ^2.4.6
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  arb_dir: lib/presentation/l10n/arb
  output_dir: lib/presentation/l10n
  class_name: Localization
  main_locale: pt_BR